# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dynamic-Material-List-Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dynamic-Material-List-Demo
	pod 'SnapKit'
	pod 'Kingfisher'
end
