# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DealWithImage-Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DealWithImage-Demo
	pod 'SnapKit'
	pod 'Kingfisher', '7.10.0'
end
