# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AutoLayout_StackView_Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AutoLayout_StackView_Demo
	pod 'SnapKit'
end
