# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Calculator-Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit', '~> 5.0'
  # Pods for Calculator-Demo

end
