# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Effect-PopView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Effect-PopView
	pod 'SnapKit'
end
